### ISSUE TITLE
WKWebView version

### ISSUE THREAD

**Issue by jeff-h** [Kapeli/HighlightedWebView#5]
Now that Dash is using WKWebView, I'm wondering if you would consider open-sourcing your new highlighting code? It's beautifully done :) I'm by no means underestimating the amount of work that must have gone into it, but I am aware of at least two other open-source Mac apps that I suspect would benefit from it ([NetNewsWire](https://github.com/brentsimmons/NetNewsWire) and [devdocs-macos](https://github.com/dteoh/devdocs-macos)).

**Comment by Kapeli** [comment]
Dash 5 uses private API in WKWebView.

See `_findString:options:maxCount:` at https://github.com/WebKit/webkit/blob/master/Source/WebKit/UIProcess/API/Cocoa/WKWebViewPrivate.h

Also: https://github.com/WebKit/webkit/blob/master/Source/WebKit/UIProcess/API/Cocoa/_WKFindOptions.h and https://github.com/WebKit/webkit/blob/master/Source/WebKit/UIProcess/API/Cocoa/_WKFindDelegate.h.

**Comment by jeff-h** [comment]
Thanks!
